### ISSUE TITLE
Help Running Monitor

### ISSUE THREAD

**Issue by serrapa** [Ch0pin/stheno#1]
Hello, I am trying to run the monitor as stated in step 2 of "Basic Usage", but I cannot find where it is. On OSX, the command "./gradlew build" did not provide any executable. Can you help me?

**Comment by Ch0pin** [comment]
Can you add here the `./gradlew build` output ?

**Comment by serrapa** [comment]
Here we are:

```
(venv) ~/tools/stheno/Intent-monitor git:main ❯ ./gradlew build

Downloading https://services.gradle.org/distributions/gradle-8.7-bin.zip
............10%.............20%.............30%.............40%............50%.............60%.............70%.............80%.............90%............100%

Welcome to Gradle 8.7!

Here are the highlights of this release:
 - Compiling and testing with Java 22
 - Cacheable Groovy script compilation
 - New methods in lazy collection properties

For more details see https://docs.gradle.org/8.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 25s
6 actionable tasks: 6 executed
```

Nothing useful I suppose, it completed successfully though

**Comment by Ch0pin** [comment]
what about this one ?
`/stheno/Intent-monitor/build/install/Intent-monitor/bin/Intent-monitor`

**Comment by serrapa** [comment]
I found the answer, inside `/stheno/Intent-monitor/build/distributions` you need to unzip `IntentMonitor.zip` and than you have the binary to run. Now I succesfully run the monitor, however I got another problem: I cannot see the intents receive from my app. I am sending a test intent with adb to see if I can see it in the monitor, but nothing appears

**Comment by serrapa** [comment]
I see this error in the monitor log:

```
org.json.JSONException: JSONObject["targetIsExported"] is not a Boolean (class org.json.JSONObject$Null : null).
	at org.json@20240303/org.json.JSONObject.wrongValueFormatException(JSONObject.java:2949)
	at org.json@20240303/org.json.JSONObject.getBoolean(JSONObject.java:647)
	at org.medusa.intentmonitor/org.medusa.intentmonitor.controllers.MainScreenController.addItem(MainScreenController.java:201)
	at org.medusa.intentmonitor/org.medusa.intentmonitor.socket.SocClient.lambda$startCommunication$0(SocClient.java:39)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Ch0pin** [comment]
I see, thanks, I'll check it out.
